version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - ./jellyfin-config:/config
      - ./media:/media
    ports:
      - 8096:8096

  rclone:
    image: rclone/rclone
    volumes:
      - ./rclone/rclone.conf:/config/rclone.conf
      - ./media:/media:shared
    command: "mount gdrive: /media --allow-other"
    privileged: true
    devices:
      - /dev/fuse
