# .github/workflows/deploy.yml
name: Deploy to Clever Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Clever Cloud CLI
      run: |
        npm install -g clever-tools
    
    - name: Deploy to Clever Cloud
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      run: |
        clever login
        clever deploy
